//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BA_Bank
    {
        public int BankID { get; set; }
        public string BankName { get; set; }
        public string AccTitle { get; set; }
        public string AccNo { get; set; }
        public string BranchCode { get; set; }
        public string BranchAdd { get; set; }
    }
}
