//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BACustomerRegistration
    {
        public int CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Address { get; set; }
        public string Customer_Eamil { get; set; }
        public Nullable<int> Customer_type { get; set; }
        public string Customer_Phone_Number { get; set; }
        public string Customer_Country { get; set; }
        public string Customer_City { get; set; }
        public Nullable<int> BusinessDivisionID { get; set; }
        public Nullable<bool> Customer_Status { get; set; }
        public string UserID { get; set; }
        public string UpdateBy { get; set; }
        public string CreateDate { get; set; }
        public string UpdateDate { get; set; }
    }
}
