//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAExpensesDropDown
    {
        public int id { get; set; }
        public string ExpenseName { get; set; }
        public Nullable<int> ExpensePrice { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
