//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAExpensesDetail
    {
        public int Trip_Expenseid { get; set; }
        public Nullable<int> TripId { get; set; }
        public Nullable<int> price { get; set; }
        public string HoRates { get; set; }
        public Nullable<int> ExpenseId { get; set; }
        public string Remarks { get; set; }
        public string ExpenseName { get; set; }
    
        public virtual BAtrip BAtrip { get; set; }
    }
}
