//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAShippingLine
    {
        public int BLShippingID { get; set; }
        public string BL { get; set; }
        public int Approval { get; set; }
        public string Shipper { get; set; }
        public string Consignee { get; set; }
        public string NotifyParty { get; set; }
        public string precarriageby { get; set; }
        public string placeofreceipt { get; set; }
        public string OceanVessel { get; set; }
        public string VoyNo { get; set; }
        public string Portoflanding { get; set; }
        public string PortofDischarge { get; set; }
        public string PlaceOfDelivery { get; set; }
        public string ContainerNo { get; set; }
        public string SealNo { get; set; }
        public string NumberOfConatinerPack { get; set; }
        public string KindOfPackagesDescriptionOfGoods { get; set; }
        public string GrossWeight { get; set; }
        public string NetWeight { get; set; }
        public string Frightandcharges { get; set; }
        public string TypeOfService { get; set; }
        public string NumberOfOrignalBL { get; set; }
        public string FrightPayable { get; set; }
        public Nullable<System.DateTime> placeOfDateofIssue { get; set; }
        public string UserID { get; set; }
        public string UpdateBy { get; set; }
        public string CreateDate { get; set; }
        public string UpdateDate { get; set; }
    }
}
