//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAtrip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAtrip()
        {
            this.BAExpensesDetails = new HashSet<BAExpensesDetail>();
            this.TripContainers = new HashSet<TripContainer>();
        }
    
        public int ID { get; set; }
        public string Trip_ID { get; set; }
        public Nullable<System.DateTime> Operation_Date { get; set; }
        public int Logistics_ID { get; set; }
        public int Drive_ID { get; set; }
        public Nullable<int> Driver2_ID { get; set; }
        public int Vechial_ID { get; set; }
        public int ContainerStatus { get; set; }
        public Nullable<System.DateTime> RecivedDate { get; set; }
        public Nullable<int> TotalExpense { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> PartyId { get; set; }
        public string PartyDriverName { get; set; }
        public string PartyDriverCNIC { get; set; }
        public string PartyDriverContactNumber { get; set; }
        public string PartyVehicleNo { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<decimal> FromLocation { get; set; }
        public Nullable<decimal> ToLocation { get; set; }
        public Nullable<int> PartyRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAExpensesDetail> BAExpensesDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TripContainer> TripContainers { get; set; }
        public virtual stp_City stp_City { get; set; }
        public virtual stp_City stp_City1 { get; set; }
        public virtual tbl_Party tbl_Party { get; set; }
    }
}
