//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClearingAgent
    {
        public long ClearingAgentId { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string ChallanNumber { get; set; }
        public System.DateTime DeleteDate { get; set; }
        public bool IsDeleted { get; set; }
    }
}
