//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Spouse
    {
        public int SpouseId { get; set; }
        public string Spouse_Name { get; set; }
        public string Date_Of_Birth { get; set; }
        public int EmpId { get; set; }
        public string Gender { get; set; }
        public string Cnic { get; set; }
    }
}
