//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string Empcode { get; set; }
        public string Employee_LastName { get; set; }
        public string Employee_FirstName { get; set; }
        public string Record_Date { get; set; }
        public string Cnic { get; set; }
        public string Date_Of_Joining { get; set; }
        public int DeptID { get; set; }
        public int CompanyId { get; set; }
        public string EmpPhoneno { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string Gender { get; set; }
        public string EmpPhonenoopt { get; set; }
        public string EmailAddress { get; set; }
        public string Address { get; set; }
        public string Date_Of_Birth { get; set; }
        public string MaritalStatus { get; set; }
    }
}
