//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmptyDropOff
    {
        public int ID { get; set; }
        public int OrderId { get; set; }
        public string OrderNo { get; set; }
        public string ContainerNo { get; set; }
        public string ContainerSize { get; set; }
        public string BLnumber { get; set; }
        public Nullable<int> PortAndTerminalId { get; set; }
        public string TerminalName { get; set; }
        public string ShippingLineName { get; set; }
        public string EIRNo { get; set; }
        public Nullable<decimal> ExpenseAtEmptyLocation { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
