//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenerateOrder
    {
        public int OrderID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> BusinessDevisionID { get; set; }
        public string OrderType { get; set; }
        public string BL { get; set; }
        public string CRO { get; set; }
        public string InBond_Number { get; set; }
        public string DeliveryNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<bool> isCompleted { get; set; }
        public Nullable<int> ShippingAgentId { get; set; }
        public Nullable<int> FreeDays { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> VesselBerthingDate { get; set; }
        public Nullable<int> ShippingLineId { get; set; }
        public string BookingPOCName { get; set; }
    }
}
