//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortAndTerminal
    {
        public long PortAndTerminalId { get; set; }
        public string PortName { get; set; }
        public string TerminalCode { get; set; }
        public string TerminalName { get; set; }
        public string Destination { get; set; }
        public string PortOfDischarge { get; set; }
        public System.DateTime DeleteDate { get; set; }
        public bool IsDeleted { get; set; }
    }
}
