//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreDispatchedMovement
    {
        public int ID { get; set; }
        public int OrderId { get; set; }
        public string OrderNo { get; set; }
        public string ContainerNo { get; set; }
        public string ContainerSize { get; set; }
        public string BLnumber { get; set; }
        public string FromLocation { get; set; }
        public Nullable<System.DateTime> FromDateTime { get; set; }
        public string ToLocation { get; set; }
        public Nullable<System.DateTime> ToDateTime { get; set; }
        public string TransporterName { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
