//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseMaster()
        {
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
        }
    
        public int PurchaseId { get; set; }
        public string PurchaseNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CreditDay { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> PartyId { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string TotalAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual tbl_Party tbl_Party { get; set; }
    }
}
