//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Requisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase_Requisition()
        {
            this.Purchase_Requisition_Detail = new HashSet<Purchase_Requisition_Detail>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> PR_DATE { get; set; }
        public Nullable<int> Department_ID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string CreateUser { get; set; }
        public string Create_IP { get; set; }
        public Nullable<System.DateTime> Create_DateTime { get; set; }
        public string UpdateUser { get; set; }
        public string Update_IP { get; set; }
        public Nullable<System.DateTime> Update_DateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Requisition_Detail> Purchase_Requisition_Detail { get; set; }
    }
}
