//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Requisition_Detail
    {
        public int ID { get; set; }
        public int Master_ID { get; set; }
        public int Item_ID { get; set; }
        public int Unit_ID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Remarks { get; set; }
    
        public virtual Purchase_Requisition Purchase_Requisition { get; set; }
    }
}
