//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_Item_Unit
    {
        public int ID { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string CreateUser { get; set; }
        public string Create_IP { get; set; }
        public Nullable<System.DateTime> Create_DateTime { get; set; }
        public string UpdateUser { get; set; }
        public string Update_IP { get; set; }
        public Nullable<System.DateTime> Update_DateTime { get; set; }
    }
}
