//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stp_ProductCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public stp_ProductCategory()
        {
            this.stp_Product = new HashSet<stp_Product>();
        }
    
        public decimal ProductCatID { get; set; }
        public string ProductCatCode { get; set; }
        public string ProductCatName { get; set; }
        public decimal CompanyID { get; set; }
        public Nullable<decimal> BusinessDivisionID { get; set; }
        public string UserID { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> ServiecTypeID { get; set; }
    
        public virtual stp_Company stp_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stp_Product> stp_Product { get; set; }
    }
}
