//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stp_Customer
    {
        public int CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string ZipCode { get; set; }
        public Nullable<decimal> CustomerAcctCode { get; set; }
        public string NTN { get; set; }
        public string SalesTaxRegNumber { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> CreditTerms { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<decimal> EmpID { get; set; }
        public decimal CityID { get; set; }
        public decimal CountryID { get; set; }
        public decimal CompanyID { get; set; }
        public Nullable<decimal> BusinessDivisionID { get; set; }
        public Nullable<decimal> CustomerTypeID { get; set; }
        public string UserID { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
