//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stp_Oil
    {
        public int OilID { get; set; }
        public Nullable<int> OilTypeID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> OilCompany { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> PaymentModeID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string PO_Ref_No { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> DeliveryNo { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<decimal> POAmount { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
    }
}
