//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stp_OilMaster
    {
        public int OMID { get; set; }
        public string Oil_Name { get; set; }
        public Nullable<int> Oil_Status { get; set; }
    }
}
