//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stp_Product
    {
        public decimal ProductID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public decimal ProductAcctCode { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public decimal ProductCatID { get; set; }
        public decimal CompanyID { get; set; }
        public Nullable<decimal> BusinessDivisionID { get; set; }
        public string UserID { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual stp_Company stp_Company { get; set; }
        public virtual stp_ProductCategory stp_ProductCategory { get; set; }
    }
}
