//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stp_ServiceType
    {
        public int ServiecTypeID { get; set; }
        public string ServiceTypeDesc { get; set; }
        public Nullable<decimal> StatusID { get; set; }
    }
}
