//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Item()
        {
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
        }
    
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> QtyLimit { get; set; }
        public string Unit { get; set; }
        public Nullable<int> ItemTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual tbl_ItemType tbl_ItemType { get; set; }
    }
}
