//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA_ERPMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleRegistrationDetail
    {
        public int VehicleID { get; set; }
        public string Vehicle_Number { get; set; }
        public int VehicleTypeID { get; set; }
        public string VehicleColor { get; set; }
        public string VehicleEngineNo { get; set; }
        public string VehicleChassisNO { get; set; }
        public string VehicleName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserID { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> TTID { get; set; }
        public string AxelType { get; set; }
        public Nullable<int> TireQuantity { get; set; }
    }
}
