// <auto-generated />
namespace BA_ERPMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dropColumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dropColumns));
        
        string IMigrationMetadata.Id
        {
            get { return "202104291936223_dropColumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
